name: Auto Start VPS
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  auto-vps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Auto VPS Session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 360
      with:
        limit-access-to-actor: False
        sudo: True
    - name: Keep Alive
      run: |
        echo "VPS is running..."
        echo "Started at: $(date)"
        sleep 360m
